### ISSUE TITLE
UI/UAT REVIEW - Homepage [Search] 

### ISSUE THREAD

**Issue by virginiaritonga** [astrajingga/template-sirclo-driveOn#7]
- [x] Font-family tidak sesuai
![Screen Shot 2021-11-02 at 10 23 11](https://user-images.githubusercontent.com/43097333/139782003-12b6edf5-59b2-4fd6-80f6-4595b5f3b3d4.png)

**Comment by Narukane** [comment]
Issue ini juga sekaligus diperbaiki pada commit : 218019bcf736f2eadf48b0adbece61c73069c817
